version: 2.0.24-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration: Release
platform: x64
shallow_clone: true
clone_folder: c:\sdl2

before_build:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
- mkdir build
- cd build
- cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release

build_script:
- nmake
# - msbuild VisualC/SDL.sln /m /p:BuildInParallel=true /p:Configuration=Release /p:Platform=x64
- ls

after_build:
- cd ..
- 7z a sdl2.zip build\SDL2.dll

artifacts:
- path: sdl2.zip
  name: SDL2
  
